# Generated by Django 4.1.2 on 2022-10-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(max_length=100)),
                ('Backend', models.BooleanField(default=True)),
                ('Age', models.IntegerField()),
                ('bio', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
