# Generated by Django 4.1.2 on 2022-10-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='myprofile',
            old_name='Backend',
            new_name='backend',
        ),
    ]
